### ISSUE TITLE
Mention Luna

### ISSUE THREAD

**Issue by hstarmans** [RobertBaruch/nmigen-tutorial#16]
Dear Robert,

You provide a nice introduction to nmigen. You should mention [Luna](https://github.com/greatscottgadgets/luna). It provides a lot of cores for nmigen.  It would also be nice if you can provide some insight into how to use such cores.
The tutorial you provide so far is more into logic. In practice, using the logic of others and their higher abstractions can help greatly in development. You also don't go into synthesizing memory and checking the output of yosys.
Furthermore, I still use apio to install yosys on a raspberry pi and it works fine. Compiling yosys and related tools is a lot of work, which i try to avoid.  People could also use tools like [yowasp](http://yowasp.org/) to get binaries.
Finally, there seem to be two versions; m-labs and the official nmigen.  It would be nice if you can touch upon possibly the politics and funding of these projects.

**Comment by XekriRedmane** [comment]
If I mentioned Luna, I'd have to find and mention every other project that uses nMigen, which isn't really a great use of my time, nor is it the purpose of the tutorial.

Also, I'm staying well clear of the m-labs thing until the dust settles. If there's a fork or renaming change, then I'll update links accordingly. Until then, there's nothing for me to do here.
