### ISSUE TITLE
7_simulating.md: Passive and active processes

### ISSUE THREAD

**Issue by kbob** [RobertBaruch/nmigen-tutorial#5]
There's a placeholder saying that you aren't clear on the active/passive distinction.  This is my understanding, based on reading the source code.  I'm not comfortable making substantive changes to your document, so I'll just leave a description here.

As I understand it, an active process keeps the simulation running.  A passive process does not.  A clock process is the canonical passive process.  The clock will run for as long as the simulation core allows it -- there'd be no point in running the simulation until the clock "finishes".

A process that steps through a test vector would be active.  You really want to finish the vector and test the results, but after that process finishes, there's no reason to continue simulating.

Pysim has two ways to run the simulation, though.  The `Simulator.run` method runs the simulation in active mode.  It will run until the last active process finishes.  The `run_until` method, when called with `run_passive` = False (the default), will run until the last active process  finishes.  Then `run_passive` is True, it will keep running when there are no active processes.

I hope that helps.

**Comment by XekriRedmane** [comment]
That seems to make sense... I'm going to run a few tests to make sure my understanding is correct, then I'll see about updating the docs. Thanks!

**Comment by XekriRedmane** [comment]
Done!
